# Generated by Django 5.0.6 on 2024-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('clothes', 'clothes'), ('footwear', 'footwear'), ('electronics', 'electronics'), ('suplements', 'suplements'), ('watches', 'watches')], max_length=50, null=True),
        ),
    ]
