# Generated by Django 5.0.6 on 2024-08-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_products_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
