# Generated by Django 5.0.6 on 2024-08-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_products_category_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
